import { useSession } from 'next-auth/react';
import Image from 'next/image';
import React from 'react'

//In typescript we define the type of the props by this way:
type Props={
    // seed? --> This means that seed might possible be a string
    // the same with large? that can also be interepreted as that 
    // we might possibly send the parameter large as well.
    seed?:string
    large?:boolean
}

function Avatar({seed, large}: Props) {
    const {data: session} = useSession();
  return (
    //Here, with 'overflow-hidden we prevent the avatar image from getting out of the circle. 
    //So the image will be inside the circle
    <div className={`relative h-10 w-10 overflow-hidden rounded-full border-gray-300 bg-white
     ${large && 'h-20 w-20'}`}>
        <Image
            // Here we are using an autogenerated avatar based on the name (for more info go to http://avatars.dcebear.com/)
            // ${session?.user?.name || 'placeholder'} means that if the user is not defined then use
            //the word placeholder to generate the avatar
            src={`https://avatars.dicebear.com/api/open-peeps/
                ${seed || session?.user?.name || 'placeholder'}.svg`}
            layout='fill'
        />
    </div>
  )
}

export default Avatar